source 'https://cdn.cocoapods.org'

install! 'cocoapods',
:generate_multiple_pod_projects => true,
:preserve_pod_file_structure => true,
:disable_input_output_paths => true

#use_modular_headers!

platform :ios, '10.0'

target :SmallEyeDemo do
    pod 'SmallEye', :path => '../'
end
